### ISSUE TITLE
TOOL: mapres greyscale converter

### ISSUE THREAD

**Issue by ChillerDragon** [Teeskins/Teeskins#10]
Use something like this https://stackoverflow.com/a/7708480

Or probably better some php or even clientside javascript library to convert mapres to a greyscale.
So a mapper can upload a custom mapres and then get for example the white version of it to animate/colorize it in the teeworlds editor.

**Comment by iTzMeRafa** [comment]
done by https://github.com/Teeskins/Teeskins/commit/7656cb83638ec81d754228532614405903319cbd

**Comment by iTzMeRafa** [comment]
![image](https://user-images.githubusercontent.com/36051055/74988752-00b8b800-543f-11ea-9ea3-7cd49a435acb.png)
