### ISSUE TITLE
Add ratelimit for downloads

### ISSUE THREAD

**Issue by ChillerDragon** [Teeskins/Teeskins#9]
It makes no sense that one ip should be able to download the same skin 100 times a minute.
This only wastes bandwith and fakes stats.

**Comment by iTzMeRafa** [comment]
Any suggestions on the rate amount?
Like only allowing 1 download each minute; per asset or in general?

**Comment by ChillerDragon** [comment]
I would at least allow two downloads per asset so one can accidentally delete the file and download it again. I would maybe go for a an max of 5-10 downloads per asset per ip in 24 hour intervals.

**Comment by iTzMeRafa** [comment]
Done by https://github.com/Teeskins/Teeskins/commit/60723ec38e94e6288adea6234de8ad9aa6a3f017

Rate-Limit: 1 minute after download, for each asset per ip
